### ISSUE TITLE
Flauschige Decken

### ISSUE THREAD

**Issue by Eisfoehniks** [maschinendeck/kanban#7]
https://www.amazon.de/WOMETO-Fleecedecke-Kuscheldecke-130x160-dunkelgrau/dp/B07FNNN747

**Comment by sezepardus** [comment]
Ist das nicht das gleiche wie: https://www.amazon.de/-/en/wometo-Blanket-Approx-Anti-Pilling-Colours/dp/B01FGJ8CRM/?
Reicht es dir wenn wir 'irgendwelche' decken holen oder hast du da spezielle ansprüche?

**Comment by Eisfoehniks** [comment]
Ich hab da keine Ansprüche, habe nur mal nen Link gepostet um zu zeigen worüber ich rede. Ich bin da offen für alles.
Ich möchte auch noch Decken mit hohem Flauschfaktor ins Rennen werfen:
https://www.ebay.de/itm/363163369047

**Comment by sezepardus** [comment]
Wir haben 4 unterschiedliche decken beim IKEA gekauft. Die liegen jetzt im deck.
